#! /usr/bin/zsh

# cdf is "cd force", i.e. "do what I mean"
#
# If there is nothing there, then make the directory and cd there.
#
# If the thing we specify is a file, then cd to the directory containing
# that file.

local d="$1"

[[ -z "$d" ]] && {
    cd
    return
}

[[ -f "$d" ]] && {
    d=${d:h}
}

mkdir -p $d && cd $d
