#! /usr/bin/zsh

# func-forget - forget all functions that came from autoloads
# set them up to be autoloaded again

local -a f
local p

for p in $fpath
do
    f=( $f $p/*(.) )
done

unfunction $f:t 2>/dev/null

autoload -U $f:t
